# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sublevelgames
email: sublevelgames@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sublevelgames is a game studio that offers a range of casual games.
  
  
#baseurl: "/cards" # the subpath of your site, e.g. /blog
url: "https://sublevelgames.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: sublevelgames

copyright:
   name: sublevelgames
   link: 'https://sublevelgames.github.io'

# Build settings
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: G-KQV1TZ0PXZ

# Comments
disqus: no
disqus-shortname: webjeda-demo

#social
facebook: 
quora: 
twitter: 
github: 
email: sublevelgames@gmail.com

#facebook like box
fb-like-box: 
fb-app-id: 
fb-page-url: 
fb-page-title: 

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

